--
Table={
[1]={
    cardlevel_id=1,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        0,
    },
    split_production={
        "common_equipment_exp",
    },
    split_production_num={
        0,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        1,
        1,
    },
    power_modulus=0,
},

[2]={
    cardlevel_id=2,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        60,
    },
    split_production={
        "common_equipment_exp",
    },
    split_production_num={
        60,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        1.1,
        1.1,
    },
    power_modulus=0.1,
},

[3]={
    cardlevel_id=3,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        100,
    },
    split_production={
        "common_equipment_exp",
    },
    split_production_num={
        160,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        1.2,
        1.2,
    },
    power_modulus=0.2,
},

[4]={
    cardlevel_id=4,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        270,
    },
    split_production={
        "common_equipment_exp",
    },
    split_production_num={
        430,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        1.3,
        1.3,
    },
    power_modulus=0.3,
},

[5]={
    cardlevel_id=5,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        330,
    },
    split_production={
        "common_equipment_exp",
    },
    split_production_num={
        760,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        1.401,
        1.401,
    },
    power_modulus=0.401,
},

[6]={
    cardlevel_id=6,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        380,
    },
    split_production={
        "common_equipment_exp",
    },
    split_production_num={
        1140,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        1.501,
        1.501,
    },
    power_modulus=0.501,
},

[7]={
    cardlevel_id=7,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        430,
    },
    split_production={
        "common_equipment_exp",
    },
    split_production_num={
        1570,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        1.602,
        1.602,
    },
    power_modulus=0.602,
},

[8]={
    cardlevel_id=8,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        490,
    },
    split_production={
        "common_equipment_exp",
    },
    split_production_num={
        2060,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        1.702,
        1.702,
    },
    power_modulus=0.702,
},

[9]={
    cardlevel_id=9,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        540,
    },
    split_production={
        "common_equipment_exp",
    },
    split_production_num={
        2600,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        1.803,
        1.803,
    },
    power_modulus=0.803,
},

[10]={
    cardlevel_id=10,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        600,
    },
    split_production={
        "common_equipment_exp",
    },
    split_production_num={
        3200,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        1.904,
        1.904,
    },
    power_modulus=0.904,
},

[11]={
    cardlevel_id=11,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        1140,
        40,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        4340,
        40,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        2.308,
        2.308,
    },
    power_modulus=1.308,
},

[12]={
    cardlevel_id=12,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1680,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        6020,
        40,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        2.409,
        2.409,
    },
    power_modulus=1.409,
},

[13]={
    cardlevel_id=13,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2220,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        8240,
        40,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        2.51,
        2.51,
    },
    power_modulus=1.51,
},

[14]={
    cardlevel_id=14,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2760,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        11000,
        40,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        2.611,
        2.611,
    },
    power_modulus=1.611,
},

[15]={
    cardlevel_id=15,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        3300,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        14300,
        40,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        2.712,
        2.712,
    },
    power_modulus=1.712,
},

[16]={
    cardlevel_id=16,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        3840,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        18140,
        40,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        2.814,
        2.814,
    },
    power_modulus=1.814,
},

[17]={
    cardlevel_id=17,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4380,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        22520,
        40,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        2.915,
        2.915,
    },
    power_modulus=1.915,
},

[18]={
    cardlevel_id=18,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4920,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        27440,
        40,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        3.017,
        3.017,
    },
    power_modulus=2.017,
},

[19]={
    cardlevel_id=19,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5460,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        32900,
        40,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        3.118,
        3.118,
    },
    power_modulus=2.118,
},

[20]={
    cardlevel_id=20,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        6000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        38900,
        40,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        3.22,
        3.22,
    },
    power_modulus=2.22,
},

[21]={
    cardlevel_id=21,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        11400,
        240,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        50300,
        280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        4.138,
        4.138,
    },
    power_modulus=3.138,
},

[22]={
    cardlevel_id=22,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        16800,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        67100,
        280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        4.24,
        4.24,
    },
    power_modulus=3.24,
},

[23]={
    cardlevel_id=23,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        22200,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        89300,
        280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        4.342,
        4.342,
    },
    power_modulus=3.342,
},

[24]={
    cardlevel_id=24,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        27600,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        116900,
        280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        4.445,
        4.445,
    },
    power_modulus=3.445,
},

[25]={
    cardlevel_id=25,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        33000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        149900,
        280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        4.547,
        4.547,
    },
    power_modulus=3.547,
},

[26]={
    cardlevel_id=26,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        38400,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        188300,
        280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        4.649,
        4.649,
    },
    power_modulus=3.649,
},

[27]={
    cardlevel_id=27,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        43800,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        232100,
        280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        4.752,
        4.752,
    },
    power_modulus=3.752,
},

[28]={
    cardlevel_id=28,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        49200,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        281300,
        280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        4.855,
        4.855,
    },
    power_modulus=3.855,
},

[29]={
    cardlevel_id=29,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        54600,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        335900,
        280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        4.957,
        4.957,
    },
    power_modulus=3.957,
},

[30]={
    cardlevel_id=30,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        60000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        395900,
        280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        5.06,
        5.06,
    },
    power_modulus=4.06,
},

[31]={
    cardlevel_id=31,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        72000,
        800,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        467900,
        1080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        5.472,
        5.472,
    },
    power_modulus=4.472,
},

[32]={
    cardlevel_id=32,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        84000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        551900,
        1080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        5.575,
        5.575,
    },
    power_modulus=4.575,
},

[33]={
    cardlevel_id=33,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        96000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        647900,
        1080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        5.678,
        5.678,
    },
    power_modulus=4.678,
},

[34]={
    cardlevel_id=34,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        108000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        755900,
        1080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        5.782,
        5.782,
    },
    power_modulus=4.782,
},

[35]={
    cardlevel_id=35,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        120000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        875900,
        1080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        5.885,
        5.885,
    },
    power_modulus=4.885,
},

[36]={
    cardlevel_id=36,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        132000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        1007900,
        1080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        5.988,
        5.988,
    },
    power_modulus=4.988,
},

[37]={
    cardlevel_id=37,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        144000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        1151900,
        1080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        6.092,
        6.092,
    },
    power_modulus=5.092,
},

[38]={
    cardlevel_id=38,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        156000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        1307900,
        1080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        6.196,
        6.196,
    },
    power_modulus=5.196,
},

[39]={
    cardlevel_id=39,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        168000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        1475900,
        1080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        6.299,
        6.299,
    },
    power_modulus=5.299,
},

[40]={
    cardlevel_id=40,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        180000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        1655900,
        1080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        6.403,
        6.403,
    },
    power_modulus=5.403,
},

[41]={
    cardlevel_id=41,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        192000,
        1600,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        1847900,
        2680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        7.34,
        7.34,
    },
    power_modulus=6.34,
},

[42]={
    cardlevel_id=42,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        204000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        2051900,
        2680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        7.444,
        7.444,
    },
    power_modulus=6.444,
},

[43]={
    cardlevel_id=43,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        216000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        2267900,
        2680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        7.548,
        7.548,
    },
    power_modulus=6.548,
},

[44]={
    cardlevel_id=44,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        228000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        2495900,
        2680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        7.652,
        7.652,
    },
    power_modulus=6.652,
},

[45]={
    cardlevel_id=45,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        240000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        2735900,
        2680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        7.757,
        7.757,
    },
    power_modulus=6.757,
},

[46]={
    cardlevel_id=46,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        252000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        2987900,
        2680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        7.861,
        7.861,
    },
    power_modulus=6.861,
},

[47]={
    cardlevel_id=47,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        264000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        3251900,
        2680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        7.966,
        7.966,
    },
    power_modulus=6.966,
},

[48]={
    cardlevel_id=48,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        276000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        3527900,
        2680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        8.071,
        8.071,
    },
    power_modulus=7.071,
},

[49]={
    cardlevel_id=49,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        288000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        3815900,
        2680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        8.175,
        8.175,
    },
    power_modulus=7.175,
},

[50]={
    cardlevel_id=50,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        300000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        4115900,
        2680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        8.28,
        8.28,
    },
    power_modulus=7.28,
},

[51]={
    cardlevel_id=51,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        318000,
        3200,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        4433900,
        5880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        8.701,
        8.701,
    },
    power_modulus=7.701,
},

[52]={
    cardlevel_id=52,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        336000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        4769900,
        5880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        8.806,
        8.806,
    },
    power_modulus=7.806,
},

[53]={
    cardlevel_id=53,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        354000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        5123900,
        5880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        8.911,
        8.911,
    },
    power_modulus=7.911,
},

[54]={
    cardlevel_id=54,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        372000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        5495900,
        5880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        9.016,
        9.016,
    },
    power_modulus=8.016,
},

[55]={
    cardlevel_id=55,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        390000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        5885900,
        5880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        9.122,
        9.122,
    },
    power_modulus=8.122,
},

[56]={
    cardlevel_id=56,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        408000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        6293900,
        5880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        9.227,
        9.227,
    },
    power_modulus=8.227,
},

[57]={
    cardlevel_id=57,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        426000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        6719900,
        5880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        9.333,
        9.333,
    },
    power_modulus=8.333,
},

[58]={
    cardlevel_id=58,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        444000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        7163900,
        5880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        9.439,
        9.439,
    },
    power_modulus=8.439,
},

[59]={
    cardlevel_id=59,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        462000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        7625900,
        5880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        9.545,
        9.545,
    },
    power_modulus=8.545,
},

[60]={
    cardlevel_id=60,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        480000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        8105900,
        5880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        9.651,
        9.651,
    },
    power_modulus=8.651,
},

[61]={
    cardlevel_id=61,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        576000,
        9600,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        8681900,
        15480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        10.606,
        10.606,
    },
    power_modulus=9.606,
},

[62]={
    cardlevel_id=62,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        672000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        9353900,
        15480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        10.712,
        10.712,
    },
    power_modulus=9.712,
},

[63]={
    cardlevel_id=63,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        768000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        10121900,
        15480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        10.819,
        10.819,
    },
    power_modulus=9.819,
},

[64]={
    cardlevel_id=64,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        864000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        10985900,
        15480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        10.925,
        10.925,
    },
    power_modulus=9.925,
},

[65]={
    cardlevel_id=65,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        960000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        11945900,
        15480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        11.032,
        11.032,
    },
    power_modulus=10.032,
},

[66]={
    cardlevel_id=66,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1056000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        13001900,
        15480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        11.138,
        11.138,
    },
    power_modulus=10.138,
},

[67]={
    cardlevel_id=67,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1152000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        14153900,
        15480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        11.245,
        11.245,
    },
    power_modulus=10.245,
},

[68]={
    cardlevel_id=68,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1248000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        15401900,
        15480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        11.352,
        11.352,
    },
    power_modulus=10.352,
},

[69]={
    cardlevel_id=69,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1344000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        16745900,
        15480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        11.459,
        11.459,
    },
    power_modulus=10.459,
},

[70]={
    cardlevel_id=70,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1440000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        18185900,
        15480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        11.566,
        11.566,
    },
    power_modulus=10.566,
},

[71]={
    cardlevel_id=71,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        1512000,
        14400,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        19697900,
        29880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        11.995,
        11.995,
    },
    power_modulus=10.995,
},

[72]={
    cardlevel_id=72,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1584000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        21281900,
        29880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        12.102,
        12.102,
    },
    power_modulus=11.102,
},

[73]={
    cardlevel_id=73,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1656000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        22937900,
        29880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        12.209,
        12.209,
    },
    power_modulus=11.209,
},

[74]={
    cardlevel_id=74,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1728000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        24665900,
        29880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        12.317,
        12.317,
    },
    power_modulus=11.317,
},

[75]={
    cardlevel_id=75,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1800000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        26465900,
        29880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        12.424,
        12.424,
    },
    power_modulus=11.424,
},

[76]={
    cardlevel_id=76,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1872000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        28337900,
        29880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        12.532,
        12.532,
    },
    power_modulus=11.532,
},

[77]={
    cardlevel_id=77,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        1944000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        30281900,
        29880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        12.64,
        12.64,
    },
    power_modulus=11.64,
},

[78]={
    cardlevel_id=78,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2016000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        32297900,
        29880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        12.748,
        12.748,
    },
    power_modulus=11.748,
},

[79]={
    cardlevel_id=79,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2088000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        34385900,
        29880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        12.856,
        12.856,
    },
    power_modulus=11.856,
},

[80]={
    cardlevel_id=80,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2160000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        36545900,
        29880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        12.964,
        12.964,
    },
    power_modulus=11.964,
},

[81]={
    cardlevel_id=81,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        2184000,
        16000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        38729900,
        45880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        13.938,
        13.938,
    },
    power_modulus=12.938,
},

[82]={
    cardlevel_id=82,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2208000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        40937900,
        45880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        14.047,
        14.047,
    },
    power_modulus=13.047,
},

[83]={
    cardlevel_id=83,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2232000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        43169900,
        45880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        14.155,
        14.155,
    },
    power_modulus=13.155,
},

[84]={
    cardlevel_id=84,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2256000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        45425900,
        45880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        14.264,
        14.264,
    },
    power_modulus=13.264,
},

[85]={
    cardlevel_id=85,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2280000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        47705900,
        45880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        14.372,
        14.372,
    },
    power_modulus=13.372,
},

[86]={
    cardlevel_id=86,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2304000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        50009900,
        45880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        14.481,
        14.481,
    },
    power_modulus=13.481,
},

[87]={
    cardlevel_id=87,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2328000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        52337900,
        45880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        14.59,
        14.59,
    },
    power_modulus=13.59,
},

[88]={
    cardlevel_id=88,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2352000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        54689900,
        45880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        14.699,
        14.699,
    },
    power_modulus=13.699,
},

[89]={
    cardlevel_id=89,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2376000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        57065900,
        45880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        14.808,
        14.808,
    },
    power_modulus=13.808,
},

[90]={
    cardlevel_id=90,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2400000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        59465900,
        45880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        14.917,
        14.917,
    },
    power_modulus=13.917,
},

[91]={
    cardlevel_id=91,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        2424000,
        17600,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        61889900,
        63480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        15.355,
        15.355,
    },
    power_modulus=14.355,
},

[92]={
    cardlevel_id=92,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2448000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        64337900,
        63480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        15.464,
        15.464,
    },
    power_modulus=14.464,
},

[93]={
    cardlevel_id=93,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2472000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        66809900,
        63480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        15.574,
        15.574,
    },
    power_modulus=14.574,
},

[94]={
    cardlevel_id=94,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2496000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        69305900,
        63480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        15.683,
        15.683,
    },
    power_modulus=14.683,
},

[95]={
    cardlevel_id=95,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2520000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        71825900,
        63480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        15.793,
        15.793,
    },
    power_modulus=14.793,
},

[96]={
    cardlevel_id=96,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2544000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        74369900,
        63480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        15.903,
        15.903,
    },
    power_modulus=14.903,
},

[97]={
    cardlevel_id=97,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2568000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        76937900,
        63480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        16.013,
        16.013,
    },
    power_modulus=15.013,
},

[98]={
    cardlevel_id=98,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2592000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        79529900,
        63480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        16.123,
        16.123,
    },
    power_modulus=15.123,
},

[99]={
    cardlevel_id=99,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2616000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        82145900,
        63480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        16.233,
        16.233,
    },
    power_modulus=15.233,
},

[100]={
    cardlevel_id=100,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2640000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        84785900,
        63480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        16.343,
        16.343,
    },
    power_modulus=15.343,
},

[101]={
    cardlevel_id=101,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        2796000,
        28000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        87581900,
        91480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        16.785,
        16.785,
    },
    power_modulus=15.785,
},

[102]={
    cardlevel_id=102,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        2952000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        90533900,
        91480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        16.896,
        16.896,
    },
    power_modulus=15.896,
},

[103]={
    cardlevel_id=103,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        3108000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        93641900,
        91480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        17.007,
        17.007,
    },
    power_modulus=16.007,
},

[104]={
    cardlevel_id=104,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        3264000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        96905900,
        91480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        17.117,
        17.117,
    },
    power_modulus=16.117,
},

[105]={
    cardlevel_id=105,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        3420000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        100325900,
        91480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        17.228,
        17.228,
    },
    power_modulus=16.228,
},

[106]={
    cardlevel_id=106,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        3576000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        103901900,
        91480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        17.339,
        17.339,
    },
    power_modulus=16.339,
},

[107]={
    cardlevel_id=107,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        3732000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        107633900,
        91480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        17.45,
        17.45,
    },
    power_modulus=16.45,
},

[108]={
    cardlevel_id=108,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        3888000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        111521900,
        91480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        17.561,
        17.561,
    },
    power_modulus=16.561,
},

[109]={
    cardlevel_id=109,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4044000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        115565900,
        91480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        17.673,
        17.673,
    },
    power_modulus=16.673,
},

[110]={
    cardlevel_id=110,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4200000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        119765900,
        91480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        17.784,
        17.784,
    },
    power_modulus=16.784,
},

[111]={
    cardlevel_id=111,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        4260000,
        32000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        124025900,
        123480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        18.23,
        18.23,
    },
    power_modulus=17.23,
},

[112]={
    cardlevel_id=112,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4320000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        128345900,
        123480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        18.342,
        18.342,
    },
    power_modulus=17.342,
},

[113]={
    cardlevel_id=113,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4380000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        132725900,
        123480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        18.454,
        18.454,
    },
    power_modulus=17.454,
},

[114]={
    cardlevel_id=114,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4440000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        137165900,
        123480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        18.566,
        18.566,
    },
    power_modulus=17.566,
},

[115]={
    cardlevel_id=115,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4500000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        141665900,
        123480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        18.678,
        18.678,
    },
    power_modulus=17.678,
},

[116]={
    cardlevel_id=116,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4560000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        146225900,
        123480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        18.79,
        18.79,
    },
    power_modulus=17.79,
},

[117]={
    cardlevel_id=117,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4620000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        150845900,
        123480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        18.902,
        18.902,
    },
    power_modulus=17.902,
},

[118]={
    cardlevel_id=118,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4680000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        155525900,
        123480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        19.014,
        19.014,
    },
    power_modulus=18.014,
},

[119]={
    cardlevel_id=119,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4740000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        160265900,
        123480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        19.126,
        19.126,
    },
    power_modulus=18.126,
},

[120]={
    cardlevel_id=120,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4800000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        165065900,
        123480,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        19.239,
        19.239,
    },
    power_modulus=18.239,
},

[121]={
    cardlevel_id=121,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        4824000,
        33600,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        169889900,
        157080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        20.592,
        20.592,
    },
    power_modulus=19.592,
},

[122]={
    cardlevel_id=122,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4848000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        174737900,
        157080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        20.705,
        20.705,
    },
    power_modulus=19.705,
},

[123]={
    cardlevel_id=123,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4872000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        179609900,
        157080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        20.817,
        20.817,
    },
    power_modulus=19.817,
},

[124]={
    cardlevel_id=124,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4896000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        184505900,
        157080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        20.93,
        20.93,
    },
    power_modulus=19.93,
},

[125]={
    cardlevel_id=125,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4920000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        189425900,
        157080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        21.043,
        21.043,
    },
    power_modulus=20.043,
},

[126]={
    cardlevel_id=126,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4944000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        194369900,
        157080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        21.157,
        21.157,
    },
    power_modulus=20.157,
},

[127]={
    cardlevel_id=127,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4968000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        199337900,
        157080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        21.27,
        21.27,
    },
    power_modulus=20.27,
},

[128]={
    cardlevel_id=128,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        4992000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        204329900,
        157080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        21.383,
        21.383,
    },
    power_modulus=20.383,
},

[129]={
    cardlevel_id=129,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5016000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        209345900,
        157080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        21.497,
        21.497,
    },
    power_modulus=20.497,
},

[130]={
    cardlevel_id=130,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5040000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        214385900,
        157080,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        21.611,
        21.611,
    },
    power_modulus=20.611,
},

[131]={
    cardlevel_id=131,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        5058000,
        34800,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        219443900,
        191880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        22.066,
        22.066,
    },
    power_modulus=21.066,
},

[132]={
    cardlevel_id=132,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5076000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        224519900,
        191880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        22.18,
        22.18,
    },
    power_modulus=21.18,
},

[133]={
    cardlevel_id=133,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5094000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        229613900,
        191880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        22.294,
        22.294,
    },
    power_modulus=21.294,
},

[134]={
    cardlevel_id=134,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5112000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        234725900,
        191880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        22.408,
        22.408,
    },
    power_modulus=21.408,
},

[135]={
    cardlevel_id=135,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5130000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        239855900,
        191880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        22.522,
        22.522,
    },
    power_modulus=21.522,
},

[136]={
    cardlevel_id=136,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5148000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        245003900,
        191880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        22.636,
        22.636,
    },
    power_modulus=21.636,
},

[137]={
    cardlevel_id=137,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5166000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        250169900,
        191880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        22.751,
        22.751,
    },
    power_modulus=21.751,
},

[138]={
    cardlevel_id=138,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5184000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        255353900,
        191880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        22.865,
        22.865,
    },
    power_modulus=21.865,
},

[139]={
    cardlevel_id=139,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5202000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        260555900,
        191880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        22.98,
        22.98,
    },
    power_modulus=21.98,
},

[140]={
    cardlevel_id=140,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5220000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        265775900,
        191880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        23.095,
        23.095,
    },
    power_modulus=22.095,
},

[141]={
    cardlevel_id=141,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        5238000,
        36000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        271013900,
        227880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        23.555,
        23.555,
    },
    power_modulus=22.555,
},

[142]={
    cardlevel_id=142,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5256000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        276269900,
        227880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        23.67,
        23.67,
    },
    power_modulus=22.67,
},

[143]={
    cardlevel_id=143,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5274000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        281543900,
        227880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        23.785,
        23.785,
    },
    power_modulus=22.785,
},

[144]={
    cardlevel_id=144,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5292000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        286835900,
        227880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        23.9,
        23.9,
    },
    power_modulus=22.9,
},

[145]={
    cardlevel_id=145,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5310000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        292145900,
        227880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        24.016,
        24.016,
    },
    power_modulus=23.016,
},

[146]={
    cardlevel_id=146,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5328000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        297473900,
        227880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        24.131,
        24.131,
    },
    power_modulus=23.131,
},

[147]={
    cardlevel_id=147,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5346000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        302819900,
        227880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        24.247,
        24.247,
    },
    power_modulus=23.247,
},

[148]={
    cardlevel_id=148,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5364000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        308183900,
        227880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        24.362,
        24.362,
    },
    power_modulus=23.362,
},

[149]={
    cardlevel_id=149,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5382000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        313565900,
        227880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        24.478,
        24.478,
    },
    power_modulus=23.478,
},

[150]={
    cardlevel_id=150,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5400000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        318965900,
        227880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        24.594,
        24.594,
    },
    power_modulus=23.594,
},

[151]={
    cardlevel_id=151,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        5412000,
        36800,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        324377900,
        264680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        25.059,
        25.059,
    },
    power_modulus=24.059,
},

[152]={
    cardlevel_id=152,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5424000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        329801900,
        264680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        25.175,
        25.175,
    },
    power_modulus=24.175,
},

[153]={
    cardlevel_id=153,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5436000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        335237900,
        264680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        25.291,
        25.291,
    },
    power_modulus=24.291,
},

[154]={
    cardlevel_id=154,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5448000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        340685900,
        264680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        25.408,
        25.408,
    },
    power_modulus=24.408,
},

[155]={
    cardlevel_id=155,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5460000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        346145900,
        264680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        25.524,
        25.524,
    },
    power_modulus=24.524,
},

[156]={
    cardlevel_id=156,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5472000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        351617900,
        264680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        25.641,
        25.641,
    },
    power_modulus=24.641,
},

[157]={
    cardlevel_id=157,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5484000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        357101900,
        264680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        25.758,
        25.758,
    },
    power_modulus=24.758,
},

[158]={
    cardlevel_id=158,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5496000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        362597900,
        264680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        25.874,
        25.874,
    },
    power_modulus=24.874,
},

[159]={
    cardlevel_id=159,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5508000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        368105900,
        264680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        25.991,
        25.991,
    },
    power_modulus=24.991,
},

[160]={
    cardlevel_id=160,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5520000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        373625900,
        264680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        26.109,
        26.109,
    },
    power_modulus=25.109,
},

[161]={
    cardlevel_id=161,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        5532000,
        37600,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        379157900,
        302280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        26.578,
        26.578,
    },
    power_modulus=25.578,
},

[162]={
    cardlevel_id=162,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5544000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        384701900,
        302280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        26.695,
        26.695,
    },
    power_modulus=25.695,
},

[163]={
    cardlevel_id=163,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5556000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        390257900,
        302280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        26.813,
        26.813,
    },
    power_modulus=25.813,
},

[164]={
    cardlevel_id=164,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5568000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        395825900,
        302280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        26.93,
        26.93,
    },
    power_modulus=25.93,
},

[165]={
    cardlevel_id=165,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5580000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        401405900,
        302280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        27.048,
        27.048,
    },
    power_modulus=26.048,
},

[166]={
    cardlevel_id=166,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5592000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        406997900,
        302280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        27.166,
        27.166,
    },
    power_modulus=26.166,
},

[167]={
    cardlevel_id=167,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5604000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        412601900,
        302280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        27.284,
        27.284,
    },
    power_modulus=26.284,
},

[168]={
    cardlevel_id=168,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5616000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        418217900,
        302280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        27.402,
        27.402,
    },
    power_modulus=26.402,
},

[169]={
    cardlevel_id=169,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5628000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        423845900,
        302280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        27.52,
        27.52,
    },
    power_modulus=26.52,
},

[170]={
    cardlevel_id=170,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5640000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        429485900,
        302280,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        27.638,
        27.638,
    },
    power_modulus=26.638,
},

[171]={
    cardlevel_id=171,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        5652000,
        38400,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        435137900,
        340680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        28.112,
        28.112,
    },
    power_modulus=27.112,
},

[172]={
    cardlevel_id=172,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5664000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        440801900,
        340680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        28.231,
        28.231,
    },
    power_modulus=27.231,
},

[173]={
    cardlevel_id=173,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5676000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        446477900,
        340680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        28.349,
        28.349,
    },
    power_modulus=27.349,
},

[174]={
    cardlevel_id=174,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5688000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        452165900,
        340680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        28.468,
        28.468,
    },
    power_modulus=27.468,
},

[175]={
    cardlevel_id=175,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5700000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        457865900,
        340680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        28.587,
        28.587,
    },
    power_modulus=27.587,
},

[176]={
    cardlevel_id=176,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5712000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        463577900,
        340680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        28.706,
        28.706,
    },
    power_modulus=27.706,
},

[177]={
    cardlevel_id=177,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5724000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        469301900,
        340680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        28.825,
        28.825,
    },
    power_modulus=27.825,
},

[178]={
    cardlevel_id=178,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5736000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        475037900,
        340680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        28.944,
        28.944,
    },
    power_modulus=27.944,
},

[179]={
    cardlevel_id=179,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5748000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        480785900,
        340680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        29.064,
        29.064,
    },
    power_modulus=28.064,
},

[180]={
    cardlevel_id=180,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5760000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        486545900,
        340680,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        29.183,
        29.183,
    },
    power_modulus=28.183,
},

[181]={
    cardlevel_id=181,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        5772000,
        39200,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        492317900,
        379880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        29.662,
        29.662,
    },
    power_modulus=28.662,
},

[182]={
    cardlevel_id=182,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5784000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        498101900,
        379880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        29.782,
        29.782,
    },
    power_modulus=28.782,
},

[183]={
    cardlevel_id=183,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5796000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        503897900,
        379880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        29.901,
        29.901,
    },
    power_modulus=28.901,
},

[184]={
    cardlevel_id=184,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5808000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        509705900,
        379880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        30.021,
        30.021,
    },
    power_modulus=29.021,
},

[185]={
    cardlevel_id=185,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5820000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        515525900,
        379880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        30.141,
        30.141,
    },
    power_modulus=29.141,
},

[186]={
    cardlevel_id=186,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5832000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        521357900,
        379880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        30.262,
        30.262,
    },
    power_modulus=29.262,
},

[187]={
    cardlevel_id=187,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5844000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        527201900,
        379880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        30.382,
        30.382,
    },
    power_modulus=29.382,
},

[188]={
    cardlevel_id=188,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5856000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        533057900,
        379880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        30.502,
        30.502,
    },
    power_modulus=29.502,
},

[189]={
    cardlevel_id=189,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5868000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        538925900,
        379880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        30.623,
        30.623,
    },
    power_modulus=29.623,
},

[190]={
    cardlevel_id=190,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5880000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        544805900,
        379880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        30.744,
        30.744,
    },
    power_modulus=29.744,
},

[191]={
    cardlevel_id=191,
    cost_item={
        "common_equipment_exp",
        "ammunition",
    },
    cost_num={
        5892000,
        40000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        550697900,
        419880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        31.227,
        31.227,
    },
    power_modulus=30.227,
},

[192]={
    cardlevel_id=192,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5904000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        556601900,
        419880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        31.348,
        31.348,
    },
    power_modulus=30.348,
},

[193]={
    cardlevel_id=193,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5916000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        562517900,
        419880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        31.469,
        31.469,
    },
    power_modulus=30.469,
},

[194]={
    cardlevel_id=194,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5928000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        568445900,
        419880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        31.59,
        31.59,
    },
    power_modulus=30.59,
},

[195]={
    cardlevel_id=195,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5940000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        574385900,
        419880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        31.711,
        31.711,
    },
    power_modulus=30.711,
},

[196]={
    cardlevel_id=196,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5952000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        580337900,
        419880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        31.833,
        31.833,
    },
    power_modulus=30.833,
},

[197]={
    cardlevel_id=197,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5964000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        586301900,
        419880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        31.954,
        31.954,
    },
    power_modulus=30.954,
},

[198]={
    cardlevel_id=198,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5976000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        592277900,
        419880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        32.076,
        32.076,
    },
    power_modulus=31.076,
},

[199]={
    cardlevel_id=199,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        5988000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        598265900,
        419880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        32.198,
        32.198,
    },
    power_modulus=31.198,
},

[200]={
    cardlevel_id=200,
    cost_item={
        "common_equipment_exp",
    },
    cost_num={
        6000000,
    },
    split_production={
        "common_equipment_exp",
        "ammunition",
    },
    split_production_num={
        604265900,
        419880,
    },
    level_effect_type={
        "power_c",
        "max_hp_c",
    },
    level_effect_value={
        32.32,
        32.32,
    },
    power_modulus=31.32,
},

}
return Table